//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BokkingId { get; set; }
        public int UserId { get; set; }
        public int HotelId { get; set; }
        public Nullable<int> RoomDescripsion { get; set; }
        public Nullable<int> RoomType { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> CurrentAmount { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
    }
}
