//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpUserName { get; set; }
        public string EmpPassword { get; set; }
        public string EmpEmail { get; set; }
        public string EmpNid { get; set; }
        public string EmpContract { get; set; }
        public System.DateTime EmpDOB { get; set; }
    }
}
