//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelInfo
    {
        public HotelInfo()
        {
            this.Users = new HashSet<User>();
        }
    
        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string HotelLocation { get; set; }
        public Nullable<int> TotalRooms { get; set; }
        public Nullable<int> AvailableRooms { get; set; }
        public Nullable<int> SingleRooms { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> ChecInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<double> SingeRoomPrice { get; set; }
        public Nullable<double> DoubleRoomPrice { get; set; }
        public Nullable<int> DoubleRooms { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
