//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int id { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string accessToken { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> expireAt { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
